name: MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8

      - name: Lint code
        run: |
          flake8 src tests

      - name: Run tests
        run: |
          pytest

      - name: Train model
        run: |
          python -m src/train_pipeline.py

      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trained-models
          path: models/